title: Aria test documentation
description: A starter page for Aria!
theme: just-the-docs

url: https://ariathaker.github.io/boom

heading_anchors: true

nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: true # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
    
aux_links:
  Template Repository: https://github.com/ariathaker/boom

  
