title: Aria test documentation
description: A starter page for Aria!
theme: just-the-docs

url: https://ariathaker.github.io/boom

heading_anchors: true

  Information about the boom database and API.
baseurl: "/boom" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ariathaker


aux_links:
  "boom on GitHub":
    - https://github.com/ariathaker/boom


nav_external_links:
  - title: OSV Schema
    url: https://ossf.github.io/osv-schema/
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: OSV-Scanner
    url: https://google.github.io/osv-scanner/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    
aux_links:
  Template Repository: https://github.com/ariathaker/boom

  

  
