title: Aria test documentation
description: A starter page for Aria!
theme: just-the-docs

url: https://ariathaker.github.io/boom

heading_anchors: true

baseurl: "/boom" # the subpath of your site, e.g. /blog

    remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

color_scheme: better_contrast
markdown: kramdown

logo: "/assets/logo.png"
favicon_ico: "/assets/icon.png"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  "OSV.dev on GitHub":
    - https://github.com/google/boom

    
aux_links:
  Template Repository: https://github.com/ariathaker/boom

  
